import MyHeader from '../src/components/myHeader/myHeader';
import ArticlePresentation from '../src/components/articlePresentation/article-presentation';
import ApprentiPage from '../src/pages/apprenti-page';
import PatronPage from '../src/pages/patron-page';
import MyInput from '../src/components/cells/myInput/my-input';
import ChercheForm from '../src/components/cherche-form';
import IndexPage from '../src/pages/index-page';
import MyInscriptForm from '../src/components/myInscriptForm/my-inscript-form';
import MaFiche from '../src/pages/ma-fiche';
import InfosPatron from '../src/components/infos-patron';
import infosApprenti from '../src/components/infos-apprenti';
import SupprFicheBtn from '../src/components/suppr-fiche-btn';
import LiACreate from '../src/components/cells/li-a-create';
import MyFooter from '../src/components/myFooter/my-footer';
import RgpdPage from '../src/pages/rgpd-page';
import HistoryLink from '../components/history-link';
import NotFound from '../src/pages/not-found';
import QuiJeSuis from '../src/components/quiNav/qui-nav';
import ResultsPage from '../src/pages/result-page';
import PrintResults from '../src/components/printResults/print-results';
import ResetPassword from '../src/pages/reset-password';
import MentionsLegales from '../src/pages/mentions-legales';
import EncartPub from '../src/components/encartPub/encart-pub';

export default function registrare() {
  customElements.define('encart-pub', EncartPub);
  customElements.define('mentions-legales', MentionsLegales);
  customElements.define('reset-password', ResetPassword);
  customElements.define('print-results', PrintResults);
  customElements.define('results-page', ResultsPage);
  customElements.define('my-header', MyHeader);
  customElements.define('article-presentation', ArticlePresentation);
  customElements.define('my-input', MyInput);
  customElements.define('index-page', IndexPage);
  customElements.define('je-suis-apprenti', ApprentiPage);
  customElements.define('je-suis-patron', PatronPage);
  customElements.define('cherche-form', ChercheForm);
  customElements.define('my-inscript-form', MyInscriptForm);
  customElements.define('ma-fiche', MaFiche);
  customElements.define('not-found', NotFound);
  customElements.define('infos-patron', InfosPatron);
  customElements.define('infos-apprenti', infosApprenti);
  customElements.define('suppr-fiche-btn', SupprFicheBtn);
  customElements.define('li-a-create', LiACreate);
  customElements.define('my-footer', MyFooter);
  customElements.define('rgpd-page', RgpdPage);
  customElements.define('history-link', HistoryLink);
  customElements.define('qui-je-suis', QuiJeSuis);
}